version: "3.5"

services:
  react-antd-typescript_build:
    build: ../
    container_name: "react-antd-typescript_build"
    volumes:
      - build:/usr/src/app/build

  react-antd-typescript_web:
    image: nginx
    ports:
      - 80:80
    container_name: "react-antd-typescript_web"
    restart: unless-stopped
    volumes:
      - build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  build: